include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - sort_child_properties_last
    - unawaited_futures
    - avoid_print
    - use_key_in_widget_constructors
